name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: codeberg.org
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ===========================================================================
  # Security Scanning Job
  # ===========================================================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy vulnerability scanner (filesystem)
        run: trivy fs --severity CRITICAL,HIGH,MEDIUM --exit-code 0 .

  # ===========================================================================
  # Build and Test Job
  # ===========================================================================
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build image for testing
      - name: Build Docker image for testing
        run: |
          docker build -t hytale-server:test .

      # Container startup test
      - name: Test container startup
        run: |
          echo "Starting container startup test..."

          # Run container with dummy tokens (will fail auth but tests container mechanics)
          docker run -d --name test-container \
            -e HYTALE_SERVER_SESSION_TOKEN=test-session \
            -e HYTALE_SERVER_IDENTITY_TOKEN=test-identity \
            -e HYTALE_SERVER_OWNER_UUID=test-uuid \
            hytale-server:test

          # Wait for container to initialize
          sleep 10

          # Check if container is running
          if docker ps | grep -q test-container; then
            echo "✓ Container started successfully"
          else
            echo "✗ Container failed to start"
            docker logs test-container
            exit 1
          fi

          # Verify Java is available in container
          docker exec test-container java -version
          echo "✓ Java runtime verified"

          # Verify entrypoint script exists and is executable
          docker exec test-container test -x /app/entrypoint.sh
          echo "✓ Entrypoint script is executable"

          # Verify downloader binary exists
          docker exec test-container test -x /app/hytale-downloader-linux-amd64
          echo "✓ Hytale downloader binary present"

          # Cleanup
          docker stop test-container
          docker rm test-container
          echo "✓ All startup tests passed"

      # Install Trivy for image scanning
      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      # Scan built image for vulnerabilities
      - name: Run Trivy vulnerability scanner (image)
        run: trivy image --severity CRITICAL,HIGH,MEDIUM --exit-code 0 hytale-server:test

  # ===========================================================================
  # Push Job (only on main branch or tags)
  # ===========================================================================
  push:
    name: Push Image
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
